config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }

  resources :boards, only: [:new, :create, :destroy]
  resources :pages, only: [:index] do
    collection do
      get :sandbox
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord

  belongs_to :user
  has_one_attached :image

  validates :name, presence: true
  validates :path, presence: true
  validates :image, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  has_many :boards, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  # uidとproviderカラムの組み合わせを一意にする
  validates :uid, presence: true, uniqueness: { scope: :provider }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github]

  # authの中身はGitHubから送られてくる大きなハッシュ。この中に名前やメアドなどが入っている。
  # providerカラムとuidカラムが送られてきたデータと一致するユーザーを探す。
  # もしユーザーが見つからない場合は新規作成する。
  def self.find_for_github_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      # 名前を取得するときはこのように書く（今回はUserモデルにname属性がないのでエラーなる） 
      # user.name = auth.info.name
      user.email = auth.info.email
      # 任意の20文字の文字列を作成する
      user.password = Devise.friendly_token[0, 20]
    end
  end
  # 最後に使います。
  def self.create_unique_string
    SecureRandom.uuid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :authenticate_user!
  
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  
  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to root_path
    else
      render "/board/new"
    end
  end

  def destroy
    board = Board.find(params[:id])
    board.destroy
    redirect_to root_path
  end

  private

  def board_params
    params.require(:board).permit(:name, :path, :image).merge(user_id: current_user.id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

    @boards = Board.where(user_id: current_user.id)
    
    @board = Board.new()

    weight_hash = FetchFitbitInfoService.fetch(FetchFitbitInfoService.apis[:weight])
    @weight_data = weight_hash[:weight]
    @min_weight = weight_hash[:min]
    @max_weight = weight_hash[:max]

    @summary_hash = FetchFitbitInfoService.fetch(FetchFitbitInfoService.apis[:summary])

  end

  def sandbox

    weight_hash = FetchFitbitInfoService.fetch(FetchFitbitInfoService.apis[:weight])
    @weight_data = weight_hash[:weight]
    @min_weight = weight_hash[:min]
    @max_weight = weight_hash[:max]

    summary_hash = FetchFitbitInfoService.fetch(FetchFitbitInfoService.apis[:summary])
    @goal_calories = summary_hash[:goal_calories_out]
    @current_calories = summary_hash[:current_calories_out]
    @goal_steps = summary_hash[:goal_steps]
    @current_steps = summary_hash[:current_steps]

  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# Deviseのコントローラーを継承することでDeviseのコントローラーと同じメソッド（つまりアクション）が使える
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def github
      # request.env["omniauth.auth"]にGitHubから送られてきたデータが入っている
      # binding.pryで確認してみましょう
      @user = User.find_for_github_oauth(request.env["omniauth.auth"])
  
      if @user.persisted? # データベースに保存されていればログイン成功
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
      else # ログイン失敗
        session["devise.github_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash = {})
    # 自作したメソッドを使いuidを必ず埋める
    hash[:uid] = User.create_unique_string
    super
  end

  protected
    def update_resource(resource, params)
      return super if params["password"]&.present?
      # 現在のパスワードなしでアカウントの更新をする
      resource.update_without_password(params.except("current_password"))
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/boards/destroy.html.erb
<h1>Boards#destroy</h1>
<p>Find me in app/views/boards/destroy.html.erb</p>

app/views/boards/new.html.erb
<div class="album py-5 bg-light">
  <div class="container">

    <div class="sidenav">
      <div class="login-main-text">
        <h2>Aplication<br>Make a new board</h2>
      </div>
    </div>

    <%= form_with model: @board do |f| %>

      <div class="main">
        <div class="col-md-6 col-sm-12">
          <div class="login-form">

            <div class="form-group">
              <%= f.label :name %><br />
              <%= f.text_field :name, autofocus: true, autocomplete: "Name", class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :path %><br />
              <%= f.text_field :path, autofocus: true, autocomplete: "URL", class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :image %><br />
              <%= f.file_field :image, autofocus: true, autocomplete: "Image", class: "form-control" %>
            </div>

          </div>
        </div>
      </div>

      <%= f.submit "Make", class: "btn btn-sm btn-secondary" %>
      
    <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>

    <title>home</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <div class="collapse bg-dark" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-7 py-4">
            <h4 class="text-white">About</h4>
            <p class="text-muted">This is an portfolio of nnoitra05. </p>
          </div>
          <div class="col-sm-4 offset-md-1 py-4">
            <h4 class="text-white">Menu</h4>
            <ul class="list-unstyled">
              <% if user_signed_in? %>
                <li><%= link_to 'Edit profile', edit_user_registration_path, class: 'text-white' %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'text-white' %></li>
                <li><%= link_to 'Play sandbox', sandbox_pages_path, class: 'text-white' %></li>
              <% else %>
                <li><%= link_to 'Sign up', new_user_registration_path, class: 'text-white' %></li>
                <li><%= link_to 'Sign in', new_user_session_path, class: 'text-white' %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
      <div class="container d-flex justify-content-between">
        <%= link_to "nnoitra05", root_path, class: "navbar-brand d-flex align-items-center" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>

  </head>

  <body>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    <%= yield %>
  
  </body>

  <footer class="text-muted">
    <div class="container">
      <p class="float-right">
      <%= link_to "Back to home", root_path %>
      </p>
    </div>
  </footer>

</html>

app/views/pages/_edit_board.html.erb
<div class="card mb-1">
  <div class="card-body">
    <p class="card-text"><%= @board.name %></p>
    <p><%= @board.path %></p>
  </div>
</div>

app/views/pages/_fitbit.html.erb
<div class="col-md-6">
  <%= bar_chart ({today: summary[:current_calories_out], goal: summary[:goal_calories_out]}), colors: ["#0dcaf0", "#6c757d"], label: "Calories", xtitle: "Calories [kcal]" %>
</div>

<div class="col-md-6">
  <%= bar_chart ({today: summary[:current_steps], goal: summary[:goal_steps]}), colors: ["#20c997", "#6c757d"], label: "Steps", xtitle: "Steps" %>
</div>

<%= area_chart @weight_data, min: @min_weight - 2, max: @max_weight + 2, label: "Weights", xtitle: "Date", ytitle: "Weights [kg]" %>

app/views/pages/create,js.erb
$("textarea").val("");
$("input").val("");
$('#exampleModal').modal('hide')
$('.posts').html("<%= escape_javascript(render 'posts', posts: @posts) %>")

app/views/pages/index.html.erb
<div class="container jumbotron">
  <h1 class="jumbotron-heading text-center">HOME</h1>
</div>

<div class="album py-5 bg-light">
  <div class="container">

    <div class="row">

      <div class="">
        <h2 class="text-center">Fitbit summary</h2>
      </div>

      <%= render partial: "fitbit", locals: {summary: @summary_hash} %>

      <hr class="my-4">

      <div class="">
        <h2 class="text-center">Customized boards</h2>
      </div>

      <% @boards.each_with_index do |board, idx| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm text-center">

            <div class="my-3 py-3">
              <p class="display-6"><%= board[:name] %></p>
            </div>
            
            <%= image_tag board.image, class: "img-fluid rounded mx-auto d-block" %>
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= button_to "View", board[:path], class: "btn btn-sm btn-outline-secondary" %>
                  <%= button_to "Delete", board_path(board[:id]), method: :delete, class: "btn btn-sm btn-outline-secondary" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <div class="col-md-4">
        <div class="card mb-4 shadow-sm text-center">

          <div class="my-3 py-3">
            <p class="display-6">Add an board</p>
          </div>

          <%= image_tag "plus.png", class: "img-fluid rounded mx-auto d-block" %>
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <%= button_to "Add", new_board_path, method: :get, class: "btn btn-sm btn-outline-secondary" %>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/pages/sandbox.html.erb
<div class="container jumbotron">
  <h1 class="jumbotron-heading text-center">SANDBOX</h1>
</div>

<div class="album py-5 bg-light">
  <div class="container">

    <div class="row">

      <div class="col-md-6">

        <%= bar_chart ({today: @current_calories, goal: @goal_calories}), colors: ["#0dcaf0", "#6c757d"], label: "Calories", xtitle: "Calories [kcal]" %>

      </div>

      <div class="col-md-6">

      <%= bar_chart ({today: @current_steps, goal: @goal_steps}), colors: ["#20c997", "#6c757d"], label: "Steps", xtitle: "Steps" %>

      </div>

    </div>

    <div class="row">

      <%= area_chart @weight_data, min: @min_weight, max: @max_weight, label: "Weights", xtitle: "Date", ytitle: "Weights [kg]" %>

    </div>

  </div>
</div>